---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_stdout_callback: yaml

  pre_tasks:

  - name: "wait 600 seconds for target connection to become reachable/usable."
    wait_for_connection:
      delay: 60
      timeout: 600

  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: ansible_env.TYPEORM_HOST
    TYPEORM_PORT: 5532
    TYPEORM_USERNAME: ansible_env.TYPEORM_USERNAME
    TYPEORM_PASSWORD: ansible_env.TYPEORM_PASSWORD
    TYPEORM_DATABASE: ansible_env.TYPEORM_DATABASE

  roles:
    - configure-node